### ISSUE TITLE
Kuka rl replacing the object after grasping

### ISSUE THREAD

**Issue by Mshz2** [mahyaret/kuka_rl#1]
Thanks for your codes..

I was wondering where can I write a code to command the kuka to relocate the block after grasping. whatever I do still the kuka joints returns the block to the start location of episode.

for example after grasping I wanted the joints get to a target location with help of calculateInverseKinematics and setJointMotorControlArray.

 Could you please help me?
best

**Comment by mahyaret** [comment]
Thanks for your question, the way this environment is designed it gives a reward whenever the object reaches to a certain height and it ends the episode. There are three files that can be modified for changing this environment behavior. kuka.py (this is the low level robot definition), kukaGymEnv.py (this is the low level environment definitions), and kuka_diverse_object_gym_env.py (this is the high-level gym environment). These files can be found under pybullet_envs. If you are new to PyBullet, I have a short introduction [here.](https://www.etedal.net/2020/04/pybullet-panda.html)

Thanks,
Mahyar

**Comment by Mshz2** [comment]
Thanks mahyar for your reply.
I took a look at your tutorial and noticed that you have defined 4 state. My aim is to add 2 more state which is  gonna be moving the grasped object to another tray location and then open the gripper joints so the object would fall into another tray. As I would like to apply this changes into your kuka_rl project I was thinking where should I add the setJointMotorControl2 command. Plus, these two extra steps should be part of entire learning process.

as a state 5,  I like to add a statement like:

``` 
#inside of Kuka.py I added below function
#self.kukaEndEffectorIndex is 6'

def move2tray(self):
    position, orientation = p.getBasePositionAndOrientation(self.kukaUid)
    t_jointPositions = p.calculateInverseKinematics(self.kukaUid, 6, [1, 1.5, 0.655],
                                                                                targetOrientation = orientation)
    p.setJointMotorControlArray(self.kukaUid, range(12), p.POSITION_CONTROL, 
                                                                     targetPositions = t_jointPositions)

#then inside of KukaDiverseObjectEnv and _step_continuous function of it, I tried to run the move2tray function after it pick object by apply_action function
def _step_continuous(self, action):
# Perform commanded action.
        self._env_step += 1
        self._kuka.applyAction(action)
        .....

        # If we are close to the bin, attempt grasp.
        state = p.getLinkState(self._kuka.kukaUid, self._kuka.kukaEndEffectorIndex)
        end_effector_pos = state[0]
        if end_effector_pos[2] <= 0.1:
            finger_angle = 0.3
            for _ in range(500):
                grasp_action = [0, 0, 0, 0, finger_angle]
                self._kuka.applyAction(grasp_action)
                p.stepSimulation()
                ......
                ......
                    
            self._attempted_grasp = True
            
        if True:                                            #in here
            self._kuka.move2tray()

        observation = self._get_observation()
        done = self._termination()
        reward = self._reward()

        debug = {'grasp_success': self._graspSuccess}
        return observation, reward, done, debug


``` 

however it does not work and just reset the env after it done the grasping just like before

**Comment by mahyaret** [comment]
I see what you mean, I think you should also edit `KukaGymEnv.py` as well. I believe there is a `_termination()` function that also responsible for determining if robot is `done`.
